name: Build LaTeX document

on:
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Deps
        run: # bash scripts/deps.sh
      - name: Build
        run: bash build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: refman
          path: ./*.pdf
